### PR TITLE
Streamlining of install instructions

### PR DESCRIPTION
**Pull request by Rovanion**
Added and tested instructions for openSUSE 12.3.

Removed BuldingOpenCaesar3.md. Instructions are now present in INSTALL_\* and README.md.

Read trough and refined README.md.

### CODE REVIEW

**Comment by dalerank** [comment]
Rovanion, pls check inscructions for windows... if possible

**Comment by gecube** [comment]
Are there any problems with windows install?

**Comment by dalerank** [comment]
Yes, need say about http://opencaesar3.org/files/resources.7z... on INSTALL_WINDOWS have no mentions of it...

**Comment by Rovanion** [comment]
Yeah someone will have to go trough INSTALL_WINDOWS and fix that like what I did for INSTALL_LINUX. It does seem to be as broken as INSTALL_LINUX was before I fixed it.

Problem is that I have no Windows installation and is therefore unable to confirm that the instructions I write are correct. I can write some instructions that should work, but I can't confirm that they work.

**Comment by dalerank** [comment]
ok... i'll fix this

**Pull request merged**
